_target_: docvce.models.task_modules.diffusion.counterfactual_diffusion.CounterfactualDiffusionModule
_partial_: true
defaults:
- _self_
- /torch_model_builder@torch_model_builder.reverse_diffusion_model: diffusers
- /torch_model_builder@torch_model_builder.classifier: local
checkpoint_configs: null
dataset_metadata: null
tb_logger: null
diffusion_steps: 1000
inference_diffusion_steps: 200
sampling_type: guided_ddpm
use_estimated_grads: false
target_query_labels: 0
start_timestep: 60
guidance_scale: 1.0
classifier_gradient_weights:
- 8.0
- 10.0
- 15.0
distance_gradient_weight: 1.0
noise_gradient_weight: 0.0
use_logits: false
enable_class_conditioning: false
use_cfg: false
use_cfg_projection: false
